version: '2'
services:

  web:
    container_name: finances-api
    tty: true
    build: docker/dev
    environment:
      - NODE_ENV=development
      - NODE_PORT=3000
      - DB_HOST=database
      - DB_PORT=5321
      - DB_USER=docker
      - DB_PASSWORD=1234
      - DB_DATABASE=finances
      - DB_PORT_TEST=5430
      - DB_DATABASE_TEST=finances_test
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5859:5859"
    volumes:
      - .:/src
    links:
      - database
      - test_database

  database:
    container_name: finances-db
    image: postgres:10.3-alpine
    environment:
      - POSTGRES_DB=finances
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    command: -p 5321
    ports:
      - "5321:5321"
  
  test_database:
    container_name: finances-db-test
    image: postgres:10.3-alpine
    environment:
      - POSTGRES_DB=finances_test
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./.data/postgresql_test:/var/lib/postgresql/data
    command: -p 5430
    ports:
      - "5430:5430"

  # database:
  #   container_name: finances-db
  #   image: postgres:9.6.2
  #   volumes:
  #     - ./.data/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
  #   environment:
  #     - POSTGRES_MULTIPLE_DATABASES="finances","finances_test"
  #     - POSTGRES_USER=docker
  #     - POSTGRES_PASSWORD=1234
  #   ports:
  #     - "5432:5432"