version: '2'
services:

  web:
    container_name: finances-api
    tty: true
    build: docker/dev
    environment:
      - NODE_ENV=development
      - NODE_PORT=3001
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=docker
      - DB_PASSWORD=1234
      - DB_DATABASE=finances
    env_file:
      - .env
    ports:
      - "3001:3001"
      - "5859:5859"
    volumes:
      - .:/src
    links:
      - database

  database:
    container_name: api-database
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_DB=finances
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    ports:
      - "3002:5432"